---

- name: Languages
  hosts: localhost
  become: true
  tasks:
    - name: Common language support
      ansible.builtin.dnf:
        name:
          - "@Development Tools"
          - cmake
          - libuv-devel
        state: present

    - name: Install R + deps
      ansible.builtin.dnf:
        name:
          - R
          - R-core-devel
          - libxml2-devel  # Needed by R's "languageserver"
        state: present
