---

- name: Install Packages
  hosts: localhost
  become: true
  vars:
    package_list:
      - git
      - vim
      - podman
      - nodejs-npm

  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name: "{{ package_list }}"
        state: present
