---
- name: Install Packages
  hosts: localhost
  become: true
  vars:
    package_list:
      - git
      - vim
      - podman
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ package_list }}"
        state: present
