---

- name: Install CRB + EPEL
  ansible.builtin.import_playbook: epel.yml

- name: Install Packages
  ansible.builtin.import_playbook: packages.yml

- name: Setup Prompt
  ansible.builtin.import_playbook: prompt.yml

- name: Setup Virtualization Host
  ansible.builtin.import_playbook: virtualization.yml

# VirtualBox doesn't work alongside KVM/libvirt.
# - name: Install VirtualBox
#   ansible.builtin.import_playbook: virtualbox.yml

# Order matters. vagrant-libvirt needs libvirt-devel which is only available if
# CodeReady Builder (CRB) is enabled.
- name: Install HashiCorp tools
  ansible.builtin.import_playbook: hashicorp.yml

- name: Install GitHub CLI
  ansible.builtin.import_playbook: gh.yml
