---

- name: Install HashiCorp Vagrant
  hosts: localhost
  # become: true
  tasks:
    - name: Install Vagrant
      become: true
      block:
        - name: Import HashiCorp GPG key
          ansible.builtin.rpm_key:
            key: https://rpm.releases.hashicorp.com/gpg
            state: present

        - name: Add HashiCorp stable repository
          ansible.builtin.yum_repository:
            name: hashicorp
            description: HashiCorp Stable - $basearch
            # yamllint disable-line rule:line-length
            baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
            gpgkey: https://rpm.releases.hashicorp.com/gpg
            gpgcheck: true
            enabled: true
            state: present

        - name: Install Vagrant
          ansible.builtin.dnf:
            name: vagrant
            state: present

        # Needs CRB which is enabled in epel.yml
        - name: Install libvirt-devel
          ansible.builtin.dnf:
            name: libvirt-devel
            state: present

    # Install plugins for ansible_user scope
    - name: Check installed vagrant plugins
      ansible.builtin.command: vagrant plugin list
      register: vagrant_plugins
      changed_when: false

    - name: Install vagrant-libvirt plugin
      when: "'vagrant-libvirt' not in vagrant_plugins.stdout"
      ansible.builtin.command: vagrant plugin install vagrant-libvirt
      register: plugin_install
      changed_when: "'Installed the plugin' in plugin_install.stdout"

    # https://github.com/projectatomic/adb-vagrant-registration
    - name: Install vagrant-registration plugin
      when: "'vagrant-registration' not in vagrant_plugins.stdout"
      ansible.builtin.command: vagrant plugin install vagrant-registration
      register: plugin_install
      changed_when: "'Installed the plugin' in plugin_install.stdout"

    - name: Add user to libvirt group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_facts['user_id'] }}"
        groups: libvirt
        append: true
